server:
  port: 3300

management:
  endpoints:
    web:
      base-path: /mgmt
      exposure:
        include: health,info,metrics,prometheus
  health:
    show-details: always
    mongo.enabled: false

management.info:
  build.enabled: true
  env.enabled: true
  java.enabled: true
  os.enabled: true

info:
  app:
    name: ${spring.application.name}
    description: RTL433 data processing pipeline for rtl_433 MQTT events
    profile: ${spring.profiles.active}

application.ingestion:
  station-name: "NOAA Weather Radio Burlington"
  station-call-sign: "KIG60"
  region-name: "South Burlington, VT"
  frequency-mhz: 162.4
